version: "3.9"

services:
  traefik:
    image: traefik:v3.0
    command:
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--log.level=DEBUG"
    ports:
      - "80:80"
      - "8080:8080"  # Dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  content:
    build:
      context: .
      dockerfile: services/content/Dockerfile
      args:
        SERVICE_NAME: content
    environment:
      - PORT=8000
    expose:
      - "8000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.content.rule=PathPrefix(`/content`)"
      - "traefik.http.routers.content.entrypoints=web"
      - "traefik.http.services.content.loadbalancer.server.port=8000"
      - "traefik.http.services.content.loadbalancer.passHostHeader=true"
      - "traefik.http.middlewares.content-strip.stripprefix.prefixes=/content"
      - "traefik.http.routers.content.middlewares=content-strip"

  assessment:
    build:
      context: .
      dockerfile: services/assessment/Dockerfile
      args:
        SERVICE_NAME: assessment
    environment:
      - PORT=8000
    expose:
      - "8000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.assessment.rule=PathPrefix(`/assessment`)"
      - "traefik.http.routers.assessment.entrypoints=web"
      - "traefik.http.services.assessment.loadbalancer.server.port=8000"
      - "traefik.http.services.assessment.loadbalancer.passHostHeader=true"
      - "traefik.http.middlewares.assessment-strip.stripprefix.prefixes=/assessment"
      - "traefik.http.routers.assessment.middlewares=assessment-strip"

  notifier:
    build:
      context: .
      dockerfile: services/notifier/Dockerfile
      args:
        SERVICE_NAME: notifier
    environment:
      - PORT=8000
    expose:
      - "8000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.notifier.rule=PathPrefix(`/notify`)"
      - "traefik.http.routers.notifier.entrypoints=web"
      - "traefik.http.services.notifier.loadbalancer.server.port=8000"
      - "traefik.http.services.notifier.loadbalancer.passHostHeader=true"
      - "traefik.http.middlewares.notifier-strip.stripprefix.prefixes=/notify"
      - "traefik.http.routers.notifier.middlewares=notifier-strip"

  tutor-chat:
    build:
      context: .
      dockerfile: services/tutor_chat/Dockerfile
      args:
        SERVICE_NAME: tutor_chat
    environment:
      - PORT=8000
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    expose:
      - "8000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.chat.rule=PathPrefix(`/chat`)"
      - "traefik.http.routers.chat.entrypoints=web"
      - "traefik.http.services.chat.loadbalancer.server.port=8000"
      - "traefik.http.services.chat.loadbalancer.passHostHeader=true"
      - "traefik.http.middlewares.chat-strip.stripprefix.prefixes=/chat"
      - "traefik.http.routers.chat.middlewares=chat-strip" 