services:
  traefik:
    image: traefik:v3.0
    command:
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.file.directory=/etc/traefik/dynamic"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--log.level=DEBUG"
      - "--experimental.plugins.jwt.modulename=github.com/traefik/plugin-jwt"
      - "--experimental.plugins.jwt.version=v0.4.0"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"  # Dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik:/etc/traefik/dynamic
      - ./keys:/keys:ro

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: tutor_auth
      POSTGRES_USER: tutor
      POSTGRES_PASSWORD: tutor
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  tutor-stack:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - PORT=8000
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - JWT_ALG=RS256
      - JWT_PUBLIC_KEY_PATH=/keys/jwtRS256.key.pub
      - DATABASE_URL=postgresql+asyncpg://tutor:tutor@db:5432/tutor_auth
      - SECRET_PRIVATE_KEY_PATH=/keys/jwtRS256.key
      - SECRET_PUBLIC_KEY_PATH=/keys/jwtRS256.key.pub
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID:-}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET:-}
    volumes:
      - ./keys:/keys:ro
    ports:
      - "8000:8000"
    depends_on:
      - db
    labels:
      - "traefik.enable=true"
      # Health check endpoint - no auth required
      - "traefik.http.routers.tutor-stack-health.rule=Host(`api.tutor-stack.local`) && PathPrefix(`/health`)"
      - "traefik.http.routers.tutor-stack-health.entrypoints=websecure"
      - "traefik.http.services.tutor-stack.loadbalancer.server.port=8000"
      # Auth endpoints - no JWT required
      - "traefik.http.routers.tutor-stack-auth.rule=Host(`api.tutor-stack.local`) && PathPrefix(`/auth`)"
      - "traefik.http.routers.tutor-stack-auth.entrypoints=websecure"
      - "traefik.http.services.tutor-stack.loadbalancer.server.port=8000"
      # Protected endpoints - JWT auth required
      - "traefik.http.routers.tutor-stack-protected.rule=Host(`api.tutor-stack.local`) && PathPrefix(`/content`, `/assessment`, `/notify`, `/chat`)"
      - "traefik.http.routers.tutor-stack-protected.entrypoints=websecure"
      - "traefik.http.routers.tutor-stack-protected.middlewares=jwt-auth@file"
      - "traefik.http.services.tutor-stack.loadbalancer.server.port=8000"

  frontend-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    labels:
      - "traefik.enable=true"
      # Frontend development routes - no auth required
      - "traefik.http.routers.frontend-dev.rule=Host(`app.tutor-stack.local`)"
      - "traefik.http.routers.frontend-dev.entrypoints=websecure"
      - "traefik.http.services.frontend-dev.loadbalancer.server.port=3000"
    depends_on:
      - tutor-stack

volumes:
  postgres_data: 