name: Deploy to Production

on:
  push:
    tags:
      - 'v*'

env:
  PYTHON_VERSION: "3.11"

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest requests

    - name: Run smoke tests
      run: |
        docker compose up --build -d
        sleep 60
        pytest tests/e2e/test_smoke.py::TestSmokeTest::test_all_endpoints -v

    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Build and push Docker images
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker build -f Dockerfile.base -t ${{ secrets.DOCKER_USERNAME }}/tutor-stack-base:${{ github.ref_name }} .
        docker build -f Dockerfile.dev -t ${{ secrets.DOCKER_USERNAME }}/tutor-stack-dev:${{ github.ref_name }} .
        docker push ${{ secrets.DOCKER_USERNAME }}/tutor-stack-base:${{ github.ref_name }}
        docker push ${{ secrets.DOCKER_USERNAME }}/tutor-stack-dev:${{ github.ref_name }} 