name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: Install linting dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 black isort mypy

    - name: Run black
      run: |
        black --check services/*/app
        black --check services/*/tests

    - name: Run isort
      run: |
        isort --check-only services/*/app
        isort --check-only services/*/tests

    - name: Run flake8
      run: |
        flake8 services/*/app
        flake8 services/*/tests

    - name: Run mypy
      run: |
        mypy services/*/app
        mypy services/*/tests 